defmodule ExMLIR.Test.Fixtures.StableHLOByte do
  @moduledoc """
  StableHLO test fixtures in byte format (MLIR bytecode).

  These fixtures are generated by serializing StableHLO text format to bytecode.
  StableHLO uses MLIR bytecode format for serialization.

  Uses `ExMLIR.StableHLOTranslate` to generate bytecode from text fixtures.
  """

  alias ExMLIR.StableHLOTranslate

  @doc """
  Generates bytecode from a text MLIR string.

  Uses `stablehlo-translate` to serialize the text to bytecode format.

  ## Options

    * `:target` - Target StableHLO version (default: "current")
    * `:allow_other_dialects` - Allow mixed dialects (default: false)
    * `:strip_debuginfo` - Strip debug info (default: false)

  ## Examples

      iex> text = ExMLIR.Test.Fixtures.StableHLOText.simple_add()
      iex> {:ok, bytecode} = ExMLIR.Test.Fixtures.StableHLOByte.from_text(text)
      {:ok, <<...>>}
  """
  def from_text(text, opts \\ []) when is_binary(text) do
    case StableHLOTranslate.check_available() do
      {:ok, _path} ->
        StableHLOTranslate.serialize(text, opts)

      {:error, :not_found} ->
        {:error, :stablehlo_translate_not_found}
    end
  end

  @doc """
  Loads a bytecode fixture from a file path.

  Returns the raw bytes of the bytecode file.
  """
  def load_from_file(path) do
    case File.read(path) do
      {:ok, bytes} -> {:ok, bytes}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Simple addition operation in bytecode format.

  Generates bytecode from the simple_add text fixture.
  """
  def simple_add_bytes(opts \\ []) do
    ExMLIR.Test.Fixtures.StableHLOText.simple_add()
    |> from_text(opts)
  end

  @doc """
  Reverse tensor operation in bytecode format.

  Generates bytecode from the reverse_tensor text fixture.
  """
  def reverse_tensor_bytes(opts \\ []) do
    ExMLIR.Test.Fixtures.StableHLOText.reverse_tensor()
    |> from_text(opts)
  end

  @doc """
  Dynamic slice operation in bytecode format.

  Generates bytecode from the dynamic_slice text fixture.
  """
  def dynamic_slice_bytes(opts \\ []) do
    ExMLIR.Test.Fixtures.StableHLOText.dynamic_slice()
    |> from_text(opts)
  end

  @doc """
  Helper to check if bytes are valid MLIR bytecode.

  MLIR bytecode starts with a magic number.
  """
  def is_bytecode?(bytes) when is_binary(bytes) do
    # TODO: MLIR bytecode magic number check
    # Actual implementation would check for MLIR bytecode header
    String.starts_with?(bytes, "ML")
  end

  @doc """
  Converts bytecode back to text format.

  Uses `stablehlo-translate` to deserialize bytecode to text.

  ## Options

    * `:print_stablehlo_version` - Print StableHLO version (default: false)

  ## Examples

      iex> {:ok, text} = ExMLIR.Test.Fixtures.StableHLOByte.to_text(bytecode)
      {:ok, "module { ... }"}
  """
  def to_text(bytes, opts \\ []) when is_binary(bytes) do
    case StableHLOTranslate.check_available() do
      {:ok, _path} ->
        StableHLOTranslate.deserialize(bytes, opts)

      {:error, :not_found} ->
        {:error, :stablehlo_translate_not_found}
    end
  end

  @doc """
  Returns a list of all available byte fixture generators.

  Each generator returns `{:ok, bytecode}` or `{:error, reason}`.
  """
  def all(opts \\ []) do
    [
      {:simple_add_bytes, fn -> simple_add_bytes(opts) end},
      {:reverse_tensor_bytes, fn -> reverse_tensor_bytes(opts) end},
      {:dynamic_slice_bytes, fn -> dynamic_slice_bytes(opts) end}
    ]
  end
end

